In [ ]:
缺失值检测

In [ ]:
# np.isnan(a): 检测是否为空值

In [3]:
import numpy as np

In [13]:
c = np.array([[1,2,3,4],[3,np.NAN,5,6],[4,5,6,np.NAN]])
c

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan,  5.,  6.],
       [ 4.,  5.,  6., nan]])

In [9]:
np.isnan(c)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [15]:
np.where(np.isnan(c))

(array([1, 2], dtype=int64), array([1, 3], dtype=int64))

In [17]:
np.argwhere(np.isnan(c))

array([[1, 1],
       [2, 3]], dtype=int64)